# A) Build Angular
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build -- --configuration production

# B) Nginx para servir SPA y proxy /api
FROM nginx:1.27-alpine
RUN rm -f /etc/nginx/conf.d/default.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# 👇 Como tu proyecto se llama "frontend", el output está en dist/frontend/
COPY dist/frontend/ /usr/share/nginx/html

EXPOSE 80
