FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ENV HOST=0.0.0.0
EXPOSE 4200
CMD ["npx","ng","serve","--host","0.0.0.0","--port","4200","--poll","--proxy-config","proxy.conf.json"]

