version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: backend/Atech/Dockerfile
    image: atech-app:latest
    container_name: atech_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "10"
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "20000"
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: "120000"
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: "180000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 20s

