FROM maven:3.9-eclipse-temurin-21-alpine
WORKDIR /app
COPY Atech/pom.xml ./pom.xml
RUN mvn -q -e -DskipTests dependency:go-offline
COPY Atech/src ./src
EXPOSE 8080
# Usa spring-boot:run con el settings si lo montas, o jar si prefieres
CMD ["mvn","spring-boot:run","-Dspring-boot.run.profiles=${SPRING_PROFILES_ACTIVE:-dev}"]




