FROM maven:3.9-eclipse-temurin-21-alpine
WORKDIR /app
COPY pom.xml ./
RUN mvn -q -e -DskipTests dependency:go-offline
COPY src ./src
EXPOSE 8080
CMD ["mvn","spring-boot:run","-Dspring-boot.run.profiles=${SPRING_PROFILES_ACTIVE:-dev}"]




